import 'package:hive/hive.dart';
import 'package:rahban/features/trip/presentation/trip_controller.dart';

part 'offline_packet.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 0)
class OfflinePacket extends HiveObject {
  @HiveField(0)
  final String tripId;

  @HiveField(1)
  final String encryptedData;

  @HiveField(2)
  final int tripStatusValue; // Storing enum as int

  @HiveField(3)
  final int timestamp;

  OfflinePacket({
    required this.tripId,
    required this.encryptedData,
    required this.tripStatusValue,
    required this.timestamp,
  });

  TripStatus get tripStatus => TripStatus.values[tripStatusValue];
}